### ISSUE TITLE
u32 assembly parsers for bitwise ops do not fail for out-of-bounds inputs

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#74] opened 2022-01-22 12:35 UTC
As specified by the assembly operations [specs](https://hackmd.io/YDbjUVHTRn64F4LPelC-NA?view#u32-operations), bitwise u32 operations should fail when given inputs >= 2^32.

Currently, the following operations do not fail correctly:
- u32and
- u32or
- u32xor

These errors should be fixed in the in the [Bitwise helper](https://github.com/maticnetwork/miden/blob/next/processor/src/bitwise/mod.rs#L80) in the processor crate.

**Comment by bobbinth** [comment] 2022-01-22 20:24
Actually, after thinking more about this, I think the issue is in the [Bitwsie helper](https://github.com/maticnetwork/miden/blob/next/processor/src/bitwise/mod.rs#L80) rather than in the assembly parser. For operations `U32and`, `U32or` and `U32xor` the bitwise helper should return an error if the inputs out of bounds - so, no need to check for the input validity at the assembly level (but we do need to fix the bitwise helper functions).

**Comment by grjte** [comment] 2022-01-23 07:16
Updated!

**Comment by bobbinth** [comment] 2022-03-03 02:50
Closed by #130

**Closed by bobbinth** 2022-03-03 02:50 UTC
Labels: bug, good first issue, processor
